### ISSUE TITLE
Repeated cross-validation

### ISSUE THREAD

**Issue by ck37** [jeremyrcoyle/origami#3]
It would be nice to support repeated cross-validation, since that is a nice way to improve precision over normal k-fold cross-validation. It's also what caret generally recommends ([example](http://topepo.github.io/caret/model-training-and-tuning.html#tune)) so a lot of people tend to use it.

Ideally it would be possible to add repeats on in an iterative manner.

**Comment by jeremyrcoyle** [comment]
Added two new features that should make this possible for origami in general.

`make_repeated_folds` will generate fold structures for repeated_cv (e.g. to do 10 repeats of 10 folds cv for 1000 observations you could do `make_repeated_folds(10,n=1000,V=10)`.

`cross_validate` now takes argument `.old_results` that will be combined (rather naively) with the results from the current call. This should allow one to add more repeats to a current result set.

 I have not added support for repeated cross-validation to `origami_SuperLearner` because we can instead integrate it into the `SuperLearner` package when we integrate origami cross-validation there.

**Comment by ck37** [comment]
Awesome, so fast! Much appreciated
